spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amigoscode-security
    username: postgres
    password: Guitarra1956
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
